spring:
    application:
        name: cafe-management-system
    datasource:
        url: jdbc:mysql://localhost:3306/cafe_management_system
        username: root
        password: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true

server:
    port: 8081
